doctor/urls.py
from django.conf.urls import url
from . import views

app_name = 'doctor'
urlpatterns = [
    #url(r'^(?P<doctor_id>[0-9]+)/$',views.index,name='index'),
    url(r'^home/$', views.index, name='index'),
    url(r'^register/$', views.DoctorFormView.as_view(), name='doctor_register'),
    url(r'^logout/$',views.Logout,name='logout'),
    url(r'^set_schedule/$',views.Set,name = 'set'),
    url(r'^set2/$',views.set_2,name="set_2"),
    url(r'^check/$',views.check,name='check'),
    url(r'^cancel/$',views.cancel,name='cancel'),
    url(r'^checkappointment/(?P<appointment_id>[0-9]+)/$',views.appointment_details,name='appointmentdetails'),
    #check_appointments
    #specify_schedule
    #See reports of patients
]

hospital/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/',include('mainpage.urls', namespace='mainpage')),
    url(r'^(/)?$',RedirectView.as_view(url='/home/')),
    url(r'^services/',include('services.urls',namespace='services')),
    url(r'^login/',RedirectView.as_view(url='/home/login/')),
    url(r'^doctor/',include('doctor.urls',namespace='doctor')),
    url(r'^patient/',include('patient.urls',namespace='patient')),
    url(r'^manager/',include('manager.urls',namespace='manager')),
]

#if settings.DEBUG:
#    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
#    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.conf.urls import url
from . import views

app_name = 'manager'
urlpatterns = [
	url(r'^home/$',views.index,name='index'),
	url(r'^doctors/$',views.view_doctors, name='viewdoctors'),
	url(r'^patients/$',views.view_patients,name='viewpatients'),
	url(r'^workers/$',views.view_workers,name='viewworkers'),
	url(r'^inventory/$',views.view_inventory,name='viewinstruments'),
	url(r'^medicines/$',views.view_medicines,name='viewmedicines'),
	url(r'^addmedicines/$',views.add_medicinedetails,name='addmedicines'),
	url(r'^addmedicine/$',views.add_medicine,name='addmedicine'),
	url(r'^addpurchasedetails/(?P<instrument_id>[0-9]+)/$',views.add_purchasedetails,name='addpurchasedetails'),
	url(r'^addinstrument/$',views.add_instrument,name='addinstrument'),
	url(r'^purchasedetails/(?P<instrument_id>[0-9]+)/$',views.view_purchasedetails,name='purchasedetails'),
	url(r'^medicinedetails/(?P<medicine_id>[0-9]+)/$',views.view_medicinedetails,name='medicinedetails'),
	url(r'^addworker/$',views.add_worker,name='addworker'),
	url(r'^rooms/$',views.view_rooms,name='viewrooms'),
	url(r'^addroom/$',views.addroom,name='addroom'),
	url(r'^labs/$',views.view_labs,name='viewlabs'),
	url(r'^addlab/$',views.addlab,name='addlab'),
	url(r'^bills/$',views.view_bills,name='viewbills'),
	url(r'^addbill/$',views.addbill,name='addbill'),
]

manager/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.contrib.auth.models import User
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.db import connection,transaction
import json
from datetime import datetime,timedelta
import re

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def index(request):
	if(request.user.is_authenticated):
		with connection.cursor() as cursor:
			cursor.execute('SELECT * from managers where user_id=%s',[request.user.id])
			x = dictfetchall(cursor)
			if(len(x)==0):
				return redirect('mainpage:index')
			context={'manager_details':x,}
			return render(request,'manager/startpage.html',context)
	else:
		return redirect('mainpage:index')

def view_doctors(request):
	if(request.user.is_authenticated):
		with connection.cursor() as cursor:
			cursor.execute('SELECT * from managers where user_id=%s',[request.user.id])
			x = dictfetchall(cursor)
			if(len(x)==0):
				return redirect('mainpage:index')
			cursor.execute('SELECT * from doctor,auth_user,doctorspeciality,lab where Doctor.lab=Lab.lab_id and Doctor.user_id = auth_user.id and Doctor.speciality = DoctorSpeciality.label')
			doctor_details = dictfetchall(cursor)
			for i in range(len(doctor_details)):

				cursor.execute('SELECT * from doctor_phone where doctor_id=%s',[doctor_details[i]['doctor_id']])
				contact_details = dictfetchall(cursor)
				cc = {'contact':''}
				if(len(contact_details)!=0):
					cc['contact']+=contact_details[0]['contact'] 	
				for j in range(1,len(contact_details)):
					cc['contact'] += str(',' + contact_details[j]['contact'])
					z = doctor_details[i].update(cc)
			print(doctor_details)
			context={"doctor_details":doctor_details,}
			return render(request,'manager/view_doctors.html',context)
	else:
		return redirect('mainpage:index')

def view_patients(request):
	if(request.user.is_authenticated):
		with connection.cursor() as cursor:
			cursor.execute('SELECT * from managers where user_id=%s',[request.user.id])
			x = dictfetchall(cursor)
			if(len(x)==0):
				return redirect('mainpage:index')
			cursor.execute('SELECT * from patients,auth_user where Patients.user_id = auth_user.id')
			patient_details = dictfetchall(cursor)
			for i in range(len(patient_details)):

				cursor.execute('SELECT * from patient_phone where patient_id=%s',[patient_details[i]['patient_id']])
				contact_details = dictfetchall(cursor)
				cc = {'contact':''}
				if(len(contact_details)!=0):
					cc['contact']+=contact_details[0]['contact'] 	
				for j in range(1,len(contact_details)):
					cc['contact'] += str(',' + contact_details[j]['contact'])
					z = patient_details[i].update(cc)
			print(patient_details)
			context={'patient_details':patient_details,}
			return render(request,'manager/view_patients.html',context)
	else:
		return redirect('mainpage:index')

def convert_date2(date):
    p = date.split('-')
    if(len(p)==1):
    	return p
    year=p[0]
    month = p[1]
    dt = p[2]
    m = {'Jan':'01','Feb':'02','Mar':'03','Apr':'04','May':'05','Jun':'06','Jul':'07','Aug':'08','Sept':'09','Oct':'10','Nov':'11','Dec':'12'}
    return str(dt + '-' + month + '-' + year)

def view_workers(request):
	if(request.user.is_authenticated):
		with connection.cursor() as cursor:
			cursor.execute('SELECT * from managers where user_id=%s',[request.user.id])
			x = dictfetchall(cursor)
			if(len(x)==0):
				return redirect('mainpage:index')
		if(request.method=='POST'):
			if(request.POST.get('workerid')):
				with connection.cursor() as cursor:
					worker_id = request.POST.get('workerid')
					cursor.execute('START TRANSACTION;')
					cursor.execute('DELETE FROM worker_phone WHERE worker_id=%s',[worker_id])
					cursor.execute('DELETE FROM worker where worker_id=%s',[worker_id])
					cursor.execute('COMMIT;')
					response_data={}
					return HttpResponse(json.dumps(response_data),content_type='application/json')
			with connection.cursor() as cursor:
				worker_id = request.POST.get('worker_id')
				worker_name = request.POST.get('worker_name')
				worker_type = request.POST.get('worker_type')
				salary = request.POST.get('salary')
				date_of_joining = request.POST.get('date_of_joining')
				print(date_of_joining)
				qualifications = request.POST.get('qualifications')
				street_no = request.POST.get('street_no')
				street_name = request.POST.get('street_name')
				apt_number = request.POST.get('apt_number')
				city = request.POST.get('city')
				state = request.POST.get('state')
				gender = request.POST.get('gender')
				account_no = request.POST.get('account_no')
				work_duration = request.POST.get('work_duration')
				contact = request.POST.get('contact')
				cursor.execute('START TRANSACTION;')
				cursor.execute('UPDATE worker SET worker_name=%s,worker_type=%s,salary=%s,date_of_joining=%s,qualifications=%s,street_no=%s,street_name=%s,apt_number=%s,city=%s,state=%s,gender=%s,account_no=%s,work_duration=%s WHERE worker_id=%s',[worker_name,worker_type,salary,date_of_joining,qualifications,street_no,street_name,apt_number,city,state,gender,account_no,work_duration,worker_id])
				cursor.execute('COMMIT;')
			response_data={}
			return HttpResponse(json.dumps(response_data),content_type='application/json')

		else:
			with connection.cursor() as cursor:
				cursor.execute('SELECT * from worker')
				worker_details = dictfetchall(cursor)
				for i in range(len(worker_details)):
					cursor.execute('SELECT * from worker_phone WHERE worker_id=%s',[worker_details[i]['worker_id']])
					contact_details = dictfetchall(cursor)
					cc={'contact':''}
					if(len(contact_details)!=0):
						cc['contact']+= contact_details[0]['phone']
					for j in range(1,len(contact_details)):
						cc['contact'] += str(',' + contact_details[j]['phone'])
					z = worker_details[i].update(cc) 
					# date = convert_date2(str(worker_details[i]['date_of_joining']))
					# cc = {'date':date}
					# z = worker_details[i].update(cc)
				context={'worker_details':worker_details,}
				return render(request,'manager/view_workers.html',context)
	else:
		return redirect('mainpage:index')

def view_inventory(request):
	if(request.user.is_authenticated):
		with connection.cursor() as cursor:
			cursor.execute('SELECT * from managers where user_id=%s',[request.user.id])
			x = dictfetchall(cursor)
			if(len(x)==0):
				return redirect('mainpage:index')
			cursor.execute('SELECT * from instrument')
			instruments = dictfetchall(cursor)
			context={'instruments':instruments,}
			return render(request,'manager/view_instruments.html',context)
	else:
		return redirect('mainpage:index')

def view_purchasedetails(request,instrument_id):
	if(request.user.is_authenticated):
		with connection.cursor() as cursor:
			cursor.execute('SELECT * from managers where user_id=%s',[request.user.id])
			x = dictfetchall(cursor)
			if(len(x)==0):
				return redirect('mainpage:index')
			cursor.execute('SELECT * from purchase_details WHERE instrument_id=%s',[instrument_id])
			instruments = dictfetchall(cursor)
			context={'instruments':instruments,'instrument_id':instrument_id,}
			return render(request,'manager/view_purchasedetails.html',context)
	else:
		return redirect('mainpage:index')
def view_medicines(request):
	if(request.user.is_authenticated):
		with connection.cursor() as cursor:
			cursor.execute('SELECT * from managers where user_id=%s',[request.user.id])
			x = dictfetchall(cursor)
			if(len(x)==0):
				return redirect('mainpage:index')
			cursor.execute('SELECT * from medicine')
			medicines = dictfetchall(cursor)
			context={'medicines':medicines,}
			return render(request,'manager/view_medicines.html',context)
	else:
		return redirect('mainpage:index')
def view_medicinedetails(request,medicine_id):
	if(request.user.is_authenticated):
		with connection.cursor() as cursor:
			cursor.execute('SELECT * from managers where user_id=%s',[request.user.id])
			x = dictfetchall(cursor)
			if(len(x)==0):
				return redirect('mainpage:index')
			cursor.execute('SELECT * from medicine_details WHERE medicine_name=%s',[medicine_id])
			medicines = dictfetchall(cursor)
			context={'medicines':medicines,'medicine_id':medicine_id,}
			return render(request,'manager/view_medicinedetails.html',context)
	else:
		return redirect('mainpage:index')
def add_medicinedetails(request):
	if(request.user.is_authenticated):
		with connection.cursor() as cursor:
			cursor.execute('SELECT * from managers where user_id=%s',[request.user.id])
			x = dictfetchall(cursor)
			if(len(x)==0):
				return redirect('mainpage:index')
			if(request.method=="POST"):
				invoice_no = request.POST.get('invoice_no')
				print(invoice_no)
				medicine = request.POST.get('medicine')
				batch_no = request.POST.get('batch_no')
				date_of_manufacture = request.POST.get('date_of_manufacture')
				date_of_expiry = request.POST.get('date_of_expiry')
				price = request.POST.get('price')
				quantity = request.POST.get('quantity')
				cursor.execute('SELECT * from medicine_details WHERE Invoice_No=%s',[invoice_no])
				det = dictfetchall(cursor)
				if(len(det)==0 and invoice_no is not None and invoice_no!=''):
					cursor.execute('START TRANSACTION;')
					cursor.execute('INSERT INTO medicine_details VALUES(%s,%s,%s,%s,%s,%s,%s)',[invoice_no,medicine,batch_no,date_of_manufacture,date_of_expiry,price,quantity])
					cursor.execute('COMMIT;')
					return redirect('manager:viewmedicines')
				else:
					cursor.execute('SELECT * from medicine')
					medicines=dictfetchall(cursor)
					context={'medicines':medicines,'error_message':'Sorry the invoice no. is invalid'}
					return render(request,'manager/add_medicinedetails.html',context)

			else:
				cursor.execute('SELECT * from medicine')

manager/templates/manager/add_instrument.html
{% extends 'manager/base.html' %}
{% block title %} Manager Home {% load staticfiles %}{% endblock %}
{% block body %}
<div class="container" style="float:right;width:75%;">
<form id="purchase" method="post" action="{% url 'manager:addinstrument' %}">
   {% csrf_token %}
  <div class="container2">
    <div class="head">
      <h2>Add Instrument</h2>
    </div>
    <label for="instrument_name">Instrument_Name</label>
    <input type="text" name="instrument_name"/><br/>
    <label for="cost_per_piece">Cost Per Piece</label>
    <input type="text" name="cost_per_piece" /><br/>
    <label for="instrument_type">Instrument Type</label>
    <input type="text" name="instrument_type"/><br />
    <button type="submit">
      Add
    </button>
  </div>
</form>
</div>
{% endblock %}

manager/templates/manager/add_lab.html
{% extends 'manager/base.html' %}
{% block title %} Manager Home {% load staticfiles %}{% endblock %}
{% block body %}
<div class="container" style="float:right;width:75%;">
<form id="purchase" method="post" action="{% url 'manager:addroom' %}">
   {% csrf_token %}
  <div class="container2">
    <div class="head">
      <h2>Add Lab</h2>
    </div>
    <label for="lab_name">Name</label>
    <input type="text" name="lab_name"/><br/>
    <label for="lab_open_time">Opening Time</label>
    <input type="time" name="lab_open_time"/><br/>
    <label for="lab_close_time">Closing Time</label>
    <input type="time" name="lab_close_time"/><br/>
    <label for="lab_description">Lab Description</label>
    <textarea rows="4" cols="50" name="lab_description"/></textarea><br/>
    
    <button type="submit">
      Add
    </button>
  </div>
</form>
</div>
{% endblock %}

manager/templates/manager/add_medicine.html
{% extends 'manager/base.html' %}
{% block title %} Manager Home {% load staticfiles %}{% endblock %}
{% block body %}
<div class="container" style="float:right;width:75%;">
<form id="purchase" method="post" action="{% url 'manager:addmedicine' %}">
   {% csrf_token %}
  <div class="container2">
    <div class="head">
      <h2>Add Medicine</h2>
    </div>
    <label for="medicine_name">Medicine_Name</label>
    <input type="text" name="medicine_name"/><br/>
    <label for="other_details">Other_details</label>
    <input type="text" name="other_details" /><br/>
    <button type="submit">
      Add
    </button>
  </div>
</form>
</div>
{% endblock %}

manager/templates/manager/add_purchasedetails.html
{% extends 'manager/base.html' %}
{% block title %} Manager Home {% load staticfiles %}{% endblock %}
{% block body %}
<div class="container" style="float:right;width:75%;">
<form id="purchase" method="post" action="{% url 'manager:addpurchasedetails' instrument_id %}">
   {% csrf_token %}
  <div class="container2">
    <div class="head">
      <h2>Add PurchaseDetails</h2>
    </div>
    {% if error_message %}
    	<h3 class="text-danger"> Sorry this is already there</h3>
    {% endif %}
    <label for="instrument_id">Instrument Id</label>
    <input type="text" name="instrument_id" value="{{ instrument_id }}" disabled=true/><br/>
    <label for="date_of_purchase">Date of Purchase</label>
    <input type="date" name="date_of_purchase" /><br/>
    <label for="count_bought">Count</label>
    <input type="text" name="count_bought"/><br />
    <label for="place_of_purchase">Place of Purchase</label>
   	<textarea type="text" name="place_of_purchase" placeholder="Address"/></textarea><br />
    <button type="submit">
      Add
    </button>
  </div>
</form>
</div>
{% endblock %}

manager/templates/manager/add_room.html
{% extends 'manager/base.html' %}
{% block title %} Manager Home {% load staticfiles %}{% endblock %}
{% block body %}
<div class="container" style="float:right;width:75%;">
<form id="purchase" method="post" action="{% url 'manager:addroom' %}">
   {% csrf_token %}
  <div class="container2">
    <div class="head">
      <h2>Add Room</h2>
    </div>
    <label for="Floor">Floor</label>
    <input type="number" name="Floor"/><br/>
    <label for="Type">Type</label>
    <input type="text" name="Type"/><br/>
    <label for="Cost_Per_Day">Cost Per Day</label>
    <input type="text" name="Cost_Per_Day"/><br/>
    <label for="room_details">Other Details</label>
    <textarea rows="4" cols="50" name="room_details"/></textarea><br/>
    
    <button type="submit">
      Add
    </button>
  </div>
</form>
</div>
{% endblock %}

manager/templates/manager/add_worker.html
{% extends 'manager/base.html' %}
{% block title %} Manager Home {% load staticfiles %}{% endblock %}
{% block body %}
<div class="container" style="float:right;width:75%;">
<form id="purchase" method="post" action="{% url 'manager:addworker' %}">
   {% csrf_token %}
  <div class="container2">
    <div class="head">
      <h2>Add Worker</h2>
    </div>
    <label for="worker_name">WorkerName</label>
    <input type="text" name="worker_name" required><br/>
    <label for="worker_type">Type</label>
    <input type="text" name="worker_type" required><br/>
    <label for="salary">Salary</label>
    <input type="text" name="salary" required><br/>
    <label for="date_of_joining">Date Of Joining</label>
    <input type="date" name="date_of_joining" required><br/>
    <label for="qualifications">Qualifications</label>
    <input type="text" name="qualifications"/><br/>
    <label for="street_no">Street No.</label>
    <input type="text" name="street_no"/><br/>
    <label for="street_name" >Street Name</label>
    <input type="text" name="street_name" required><br/>
    <label for="apt_number">Apt Number</label>
    <input type="text" name="apt_number"/><br/>
    <label for="city">City</label>
    <input type="text" name="city" required><br/>
    <label for="state">State</label>
    <input type="text" name="state" required><br/>
    <label for="gender">Gender</label>
    <select name="gender">
      <option value="M">M</option>
      <option value="F">F</option>
    </select><br/>
    <label for="account_no" >Account No.</label>
    <input type="text" name="account_no" required><br/>
    <label for="work_duration" >Work Duration</label>
    <input type="text" name="work_duration" required><br/>
    <label for="contact">Contact No.</label>
    <input type="text" name="contact"/><br/>
    <button type="submit">
      Add
    </button>
  </div>
</form>
</div>
{% endblock %}

manager/templates/manager/view_bills.html
{% extends 'manager/base.html' %}
{% block title %} Manager Home {% load staticfiles %}{% endblock %}
{% block body %}
<div class="container" style="float:right;width:75%;">
<table id="docs">
  <tr>
    <th>Bill_No</th>
    <th>Bill_date</th>
    <th>Patient_Id</th>
    <th>Doc_Charges</th>
    <th>Room_Charges</th>
    <th>Medicine_Charges</th>
    <th>Service_Charges</th>
    <th></th>
  </tr>
  {% for i in bills %}
  		<tr>
  		<td>{{ i.bill_no }}</td>
  		<td>{{ i.bill_date }}</td>
  		<td>{{ i.patient_id }}</td>
  		<td>{{ i.doc_charges }}</td>
      <td>{{ i.room_charges }}</td>
      <td>{{ i.medicine_charges }}</td>
      <td>{{ i.service_charges }}</td>
  		<td><button class="btn btn-success bill_update" uid="{{ i.bill_no }}" n="{{ i.bill_date | date:'Y-m-d' }}" t = "{{ i.patient_id }}" s="{{ i.doc_charges }}" d = "{{ i.room_charges }}" q = "{{ i.medicine_charges }}" sn = "{{ i.service_charges }}">Update</button>
      <button class="btn btn-danger bill_delete" u="{{ i.bill_no }}">Delete</button></td>
  		</tr>
  {% endfor %}
 </table>
 <button class="btn btn-success addbill">Add Bill</button>
</div>
<button id="modals2" hidden></button>
<div id="Modal_update2" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>

         <form method="post">
            {% csrf_token %}
            <label for="bill_date">Bill Date</label>
            <input class="bill_date" type = "date" name="bill_date" id="bill_date"><br>
            <label for="patient_id">Patient Id</label>
            <input class="patient_id2" type = "text" name = "patient_id" id="patient_id2" disabled><br>
            <label for="doc_charges">Doc Charges</label>
            <input class="doc_charges" type="number" step="0.01" name = "doc_charges" id="doc_charges"><br>
            <label for="room_charges">Room Charges</label>
            <input class="room_charges" name="room_charges" type="number" step="0.01"><br>
            <label for="medicine_charges">Medicine Charges</label>
            <input class="medicine_charges" name = "medicine_charges" type="number" step="0.01"><br>
            <label for="service_charges">Service Charges</label>
            <input class="service_charges" name = "service_charges" type="number" step="0.01"><br>
            <input class="bill_no" type="text" name = "bill_no" hidden>
            <input type="submit" id="submitupdate2">
         </form>
    </div>


</div>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    var btn = document.getElementById("modals2");
    var modal = document.getElementById("Modal_update2");
    var span = document.getElementsByClassName("close")[0];
    btn.onclick = function() {
        modal.style.display = "block";
    }

    span.onclick = function() {
        modal.style.display = "none";
    }
	$('.bill_update').click(function(){
    $('#modals2').click();
    $('.bill_no').val($(this).attr('uid'));
    $('.bill_date').val($(this).attr('n'));
    $('.patient_id2').val($(this).attr('t'));
    $('.doc_charges').val($(this).attr('s'));
    $('.room_charges').val($(this).attr('d'));
    $('.medicine_charges').val($(this).attr('q'));
    $('.service_charges').val($(this).attr('sn'));
    
	});

  $('#submitupdate2').click(function(){
    $.ajax({
          type:"POST",
          url:"{% url 'manager:viewbills' %}",
          data:{"bill_no":$(".bill_no").val(),"patient_id":$(".patient_id2").val(),"bill_date":$(".bill_date").val(),"doc_charges":$(".doc_charges").val(),"room_charges":$(".room_charges").val(),"medicine_charges":$(".medicine_charges").val(),"service_charges":$(".service_charges").val(),
          "csrfmiddlewaretoken":"{{csrf_token}}"},
      }).done(function(request){
        window.location.href="{% url 'manager:viewbills' %}";
          
      }).fail(function(){
        window.location.href="{% url 'manager:viewbills' %}";
      });
    
  });
  $('.bill_delete').click(function(){
    $.ajax({
          type:"POST",
          url:"{% url 'manager:viewbills' %}",
          data:{"billno":$(this).attr('u'),"csrfmiddlewaretoken":"{{csrf_token}}"},
      }).done(function(request){
        window.location.href="{% url 'manager:viewbills' %}";
          
      }).fail(function(){
        window.location.href="{% url 'manager:viewbills' %}";
      });
  });
  $('.addbill').click(function(){
    window.location.href="{% url 'manager:addbill' %}";
  })
</script>
{% endblock %}

manager/templates/manager/view_instruments.html
{% extends 'manager/base.html' %}
{% block title %} Manager Home {% load staticfiles %}{% endblock %}
{% block body %}
<div class="container" style="float:right;width:75%;">
	<table id="docs">
  <tr>
    <th>Instrument Id</th>
    <th>Instrument Name</th>
    <th>Cost_per_piece</th>
    <th>Instrument_Type</th>
    <th>Further Details</th>
  </tr>
  {% for i in instruments %}
  		<tr>
  		<td>{{ i.instrument_id }}</td>
  		<td>{{ i.instrument_name }}</td>
  		<td>{{ i.cost_per_piece }}</td>
  		<td>{{ i.instrument_type }}</td>
  		<td><button class="btn btn-success details" u="{{ i.instrument_id }}"> More Details</button></td>
  		</tr>
  {% endfor %}
 </table>
 <button class="btn btn-success addinstrument">Add Instrument</button>
 </div>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
	$('.details').click(function(){
		var v = $(this).attr('u');
    window.location.href="/manager/purchasedetails/" + v +"/";
		
	});

  $('.addinstrument').click(function(){
    window.location.href="{% url 'manager:addinstrument' %}";
  })
</script>
{% endblock %}

manager/templates/manager/view_labs.html
{% extends 'manager/base.html' %}
{% block title %} Manager Home {% load staticfiles %}{% endblock %}
{% block body %}
<div class="container" style="float:right;width:75%;">
	<table id="docs">
  <tr>
    <th>Lab Id</th>
    <th>Name</th>
    <th>Opening Time</th>
    <th>Closing Time</th>
    <th>No_Doctors</th>
    <th>No_Workers</th>
    <th>Lab_Description</th>
  </tr>
  {% for i in labs %}
  		<tr>
  		<td>{{ i.lab_id }}</td>
  		<td>{{ i.lab_name }}</td>
      <td>{{ i.lab_open_time }}</td>
  		<td>{{ i.lab_close_time }}</td>
  		<td>{{ i.no_doctors }}</td>
      <td>{{ i.no_workers }}</td>
      <td>{{i.lab_description}}</td>
  		</tr>
  {% endfor %}
 </table>
 <button class="btn btn-success addlab">Add Lab</button>
 </div>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
  $('.addlab').click(function(){
    window.location.href="{% url 'manager:addlab' %}";
  })
</script>
{% endblock %}