doctor/urls.py
from django.conf.urls import url
from . import views

app_name = 'doctor'
urlpatterns = [
    #url(r'^(?P<doctor_id>[0-9]+)/$',views.index,name='index'),
    url(r'^home/$', views.index, name='index'),
    url(r'^register/$', views.DoctorFormView.as_view(), name='doctor_register'),
    url(r'^logout/$',views.Logout,name='logout'),
    url(r'^set_schedule/$',views.Set,name = 'set'),
    url(r'^set2/$',views.set_2,name="set_2"),
    url(r'^check/$',views.check,name='check'),
    url(r'^cancel/$',views.cancel,name='cancel'),
    url(r'^checkappointment/(?P<appointment_id>[0-9]+)/$',views.appointment_details,name='appointmentdetails'),
    #check_appointments
    #specify_schedule
    #See reports of patients
]

hospital/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/',include('mainpage.urls', namespace='mainpage')),
    url(r'^(/)?$',RedirectView.as_view(url='/home/')),
    url(r'^services/',include('services.urls',namespace='services')),
    url(r'^login/',RedirectView.as_view(url='/home/login/')),
    url(r'^doctor/',include('doctor.urls',namespace='doctor')),
    url(r'^patient/',include('patient.urls',namespace='patient')),
    url(r'^manager/',include('manager.urls',namespace='manager')),
]

#if settings.DEBUG:
#    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
#    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

doctor/models.py
#from django.db import models
#from django import forms
#from django.contrib.auth.models import User
#from django.contrib import admin
# Create your models here.
#class Doctor(models.Model):
#    username = models.CharField(max_length=100,unique=True)
#    password = models.CharField(max_length=128)
#    name = models.CharField(max_length=100)
#    specialization = models.CharField(max_length=100)
'''class DoctorSpeciality(models.Model):
    speciality = models.CharField(max_length=30)
    label = models.CharField(max_length=10,primary_key=True)
    def __unicode__(self):
        return self.speciality

    def __str__(self):
        return self.speciality

    class Meta:
        verbose_name_plural = 'Doctors specialties'

class DoctorSpecialityAdmin(admin.ModelAdmin):
    search_fields = ('speciality', )




class Doctor(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    is_doctor = models.BooleanField(default=True)
    speciality = models.ForeignKey(DoctorSpeciality,default="Other")
    specialization = models.CharField(max_length=100)
    certification_CHOICES = (
        ('A', 'American Board'),
        ('B', 'Bachelor'),
    )
    certification = models.CharField(max_length=30, choices=certification_CHOICES)

    def __unicode__(self):
        return self.user.first_name + ' ' + self.user.last_name
    '''

doctor/forms.py
from django import forms
#from hospital.mainpage.models import Doctor
#from .models import Doctor,DoctorSpeciality
from django.db import connection

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

class DoctorForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    username = forms.CharField(max_length=200)
    email = forms.CharField(max_length=200)
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    with connection.cursor() as cursor:
        cursor.execute('SELECT * from doctorspeciality')
        doctor_specialities = dictfetchall(cursor)
    specialities=[]
    for obj in doctor_specialities:
        specialities.append((obj['label'],obj['speciality']))
    specialdd = tuple(specialities)
    speciality = forms.ChoiceField(choices=specialdd,required=True)
    degree = forms.CharField(max_length=30)
    with connection.cursor() as cursor:
        cursor.execute('SELECT * from lab')
        doctor_lab = dictfetchall(cursor)
    labs=[]
    for obj in doctor_lab:
        labs.append((obj['lab_id'],obj['lab_name']))
    labs.append(("0","None"))
    labd = tuple(labs)
    lab = forms.ChoiceField(choices=labd,required=True)
    Street_no = forms.CharField(max_length=10, required=True)
    Street_Name = forms.CharField(max_length=100,required=True)
    Apt_number = forms.CharField(max_length=10)
    City = forms.CharField(max_length=10,required=True)
    State = forms.CharField(max_length=20)
    Zip_code = forms.CharField(max_length=10)
    Gender = forms.ChoiceField(choices = (('M','M'),('F','F')),required=True)
    Work_Duration = forms.CharField(max_length=10)
    Account_No = forms.CharField(max_length=15,required=True)
    contact = forms.CharField(max_length=100,required=True)


    #class Meta:
    #    model = Doctor
    #    fields = ['username','email','password','first_name','last_name','specialityD','specialization','certification']
        #widgets = {
        #    'name': forms.TextInput(attrs={'placeholder': 'What\'s your name?'}),
        #    'email': forms.TextInput(attrs={'placeholder': 'john@example.com'}),
        #    'gist': forms.TextInput(attrs={'placeholder': 'In a few words, I\'m looking for/to...'}),
        #    'expire': forms.TextInput(attrs={'placeholder': 'MM/DD/YYYY'})
        #}

doctor/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .forms import DoctorForm
from django.contrib.auth.models import User
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.db import connection,transaction
import json
from datetime import datetime,timedelta
import re
import smtplib

# Create your views here.
#def index(request,doctor_id):
    #if(request.user)
def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def xyz(history,stri):
    for i in range(len(history)):
        sched = history[i]
        year = sched[stri].year
        month = months[str(sched[stri].month)]
        dt = sched[stri].day
        history[i]['year']=year
        history[i]['month']=month
        history[i]['dt']=dt
    return history

def convert_date(date):
    p = date.split(' ')
    month = p[0][:-1]
    date = p[1][:-1]
    year = p[2]
    m = {'Jan':'01','Feb':'02','Mar':'03','Apr':'04','May':'05','Jun':'06','Jul':'07','Aug':'08','Sept':'09','Oct':'10','Nov':'11','Dec':'12'}
    month = m[month]
    return str(year + '-' + month + '-' + date)

def convert_time(time):
    if(time=="noon"):
        return str("12:00")
    t = time.split(' ')
    d = t[0].split(':')
    if(len(d)==1):
        t[0] = t[0] + ':00'

    if(t[1]=="a.m."):
        return t[0]
    else:
        d = t[0].split(':')
        d[0] = str(int(d[0]) + 12)
        return str(d[0]+':'+t[1])
        
months = {'1':'January','2':'February','3':'March','4':'April','5':'May','6':'June','7':'July','8':'August','9':'September','10':'October','11':'November','12':'December'}
def index(request):
    if(request.method=="POST"):
        if(request.user.is_authenticated):
            with connection.cursor() as cursor:

                cursor.execute('SELECT * from doctor WHERE user_id=%s',[request.user.id])
                doctor_details = dictfetchall(cursor)
                if(len(doctor_details)==1):
                    start_time = request.POST.get('start_time')
                    end_time = request.POST.get('end_time')
                    examination_date = request.POST.get('examination_date')
                    Outcome = request.POST.get('Outcome')
                    Treatment = request.POST.get('Treatment')
                    start_time = convert_time(str(start_time))
                    end_time = convert_time(str(end_time))
                    examination_date = convert_date(str(examination_date))
                    cursor.execute('START TRANSACTION;')
                    cursor.execute('UPDATE examination SET Outcome=%s, Treatment=%s,is_done=%s WHERE examination_date=%s and start_time=%s and end_time=%s and doctor_id=%s',[Outcome,Treatment,'1',examination_date,start_time,end_time,doctor_details[0]['doctor_id']])
                    cursor.execute('COMMIT;')
                    response_data={}
                    return HttpResponse(json.dumps(response_data),content_type='application/json')
                else:
                    response_data={}
                    return HttpResponse(json.dumps(response_data),content_type='application/json')
        else:
            status = 500
            response_data={}
            response = HttpResponse(json.dumps(response_data),content_type='application/json')
            response.status_code=status
            return response

    template = loader.get_template('doctor/doctor_loggedin.html')
    with connection.cursor() as cursor:
        if request.user.is_authenticated:
            cursor.execute('SELECT * from doctor where user_id = %s',[request.user.id])
            doctor_details = dictfetchall(cursor)
            if len(doctor_details)>=1:
                cursor.execute('SELECT * from schedule WHERE doctor_id=%s',[doctor_details[0]['doctor_id']])
                schedule = dictfetchall(cursor)
                for i in range(len(schedule)):
                    sched = schedule[i]
                    year = sched['date'].year
                    month = months[str(sched['date'].month)]
                    dt = sched['date'].day
                    schedule[i]['year']=year
                    schedule[i]['month']=month
                    schedule[i]['dt']=dt
                now = datetime.now()
                now2 = datetime.now() + timedelta(days=2)
                year = now.year
                month = now.month
                day = now.day
                cursor.execute('SELECT * FROM examination,diseases,patients,auth_user WHERE doctor_id=%s and examination.disease = diseases.disease_id and examination.patient_id=patients.patient_id and patients.user_id = auth_user.id and ((examination.examination_date < cast(now() as date)) OR ((examination.examination_date=cast(now() as date)) AND (examination.start_time<cast(now() as time))))',[doctor_details[0]['doctor_id']])
                examinations = dictfetchall(cursor)
                cursor.execute('SELECT * FROM examination,diseases,patients,auth_user WHERE doctor_id=%s and examination.disease = diseases.disease_id and examination.patient_id=patients.patient_id and patients.user_id = auth_user.id and ((examination.examination_date >cast(now() as date)) OR (examination.examination_date = cast(now() as date) AND examination.start_time>=cast(now() as time)))',[doctor_details[0]['doctor_id']])
                upcoming_examinations = dictfetchall(cursor)
                cursor.execute('SELECT * from schedule WHERE doctor_id=%s and is_appointment=true and date >= cast(now() as date) and date<= cast((now() + interval 2 day) as date)',[doctor_details[0]['doctor_id']])
                appts = dictfetchall(cursor)
                appts = xyz(appts,'date')
                upcoming_examinations = xyz(upcoming_examinations,'examination_date')
                examinations = xyz(examinations,'examination_date')
                exams = []
                for i in range(len(examinations)):
                    exams.append((i,examinations[i]))
                cursor.execute('SELECT DISTINCT patient_id from examination WHERE doctor_id=%s and is_done=1 and (examination_date<cast(now() as date) or (examination_date=cast(now() as date) and start_time<cast(now() as time)))',[doctor_details[0]['doctor_id']])
                patients = dictfetchall(cursor)
                patient_det = []
                for i in patients:
                    cursor.execute('SELECT * from patients,auth_user WHERE patient_id=%s and patients.user_id=auth_user.id',[i['patient_id']])
                    pp = dictfetchall(cursor)
                    patient_det.append(pp[0])
                context = {'patients':patient_det,'doctor':doctor_details[0],'schedule':schedule,'appointments':appts,'examinations':exams,'upcoming_examinations':upcoming_examinations,}
            else:
                return HttpResponse("<h2>You need to log in as a doctor, first to access this page</h2>")
        else:
            return HttpResponse("<h2> You need to log in as a doctor, first to access this page</h2>")
        return render(request,'doctor/doctor_loggedin.html',context)


class DoctorFormView(View):
    form_class = DoctorForm
    template_name = 'doctor/registration_form.html'
    cursor = connection.cursor()
    #display blank form
    def get(self,request):
        form = self.form_class(None)
        user_type=-1
        if(request.user.is_authenticated):
            cursor.execute('SELECT * FROM doctor where user_id=%s',[request.user.id])
            is_doc = dictfetchall(cursor)
            if(len(is_doc)==0):
                cursor.execute('SELECT * from patients where user_id=%s',[request.user.id])
                is_pat = dictfetchall(cursor)
                if(len(is_pat)==0):
                    user_type=2
                else:
                    user_type=1
            else:
                user_type=0
        return render(request,self.template_name,{'form':form,'user_type':user_type,})

    #process form data
    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            cursor = connection.cursor()
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            first_name=form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            degree = form.cleaned_data['degree']
            Street_no = form.cleaned_data['Street_no']
            Street_Name = form.cleaned_data['Street_Name']
            Apt_number = form.cleaned_data['Apt_number']
            City = form.cleaned_data['City']
            State = form.cleaned_data['State']
            Zip_code = form.cleaned_data['Zip_code']
            Gender = form.cleaned_data['Gender']
            Work_Duration = form.cleaned_data['Work_Duration']
            Account_No = form.cleaned_data['Account_No']
            contact = form.cleaned_data['contact']
            contacts = re.findall(r"[0-9]+",contact)
            final_contacts=set()
            for i in contacts:
                if(len(i)==11 and i[0]=='0'):
                    final_contacts.add(i[1:])

                elif (len(i)==10):
                    final_contacts.add(i)
                elif (len(i)==13 and i[0]=='+'):
                    final_contacts.add(i[3:])

            #cursor.execute('SELECT * from DoctorSpeciality where label=form.cleaned_data['specialityD'])
            #speciality = DoctorSpeciality.objects.raw('SELECT * from doctor_DoctorSpeciality where label = %s',[form.cleaned_data['specailityD']])
            speciality = form.cleaned_data['speciality']
            lab = form.cleaned_data['lab']
            try:
                User.objects.get(username=username)

doctor/templates/doctor/doctor_reg_appointments.html
{% extends 'doctor/base.html' %}
{% block title %} RegisteredAppointmentDetail{%load staticfiles %}{% endblock %}

{% block body %}
    <h1>Appointment_Details</h1><br>

    <h3>Patient_Name:</h3>{{ appointment_details.username }}<br>
<h3>Patient_first_name:</h3>{{ appointment_details.first_name }}<br>
<h3>Patient_last_name:</h3>{{ appointment_details.last_name }}<br>
<h3>Patient_email:</h3>{{ appointment_details.email }}<br>
<h3>Patient_type:</h3>{{ appointment_details.type }}<br>
<h3>Patient_DOB:</h3>{{ appointment_details.DOB }}<br>
<h3>Patient_contact_no:</h3>{{ appointment_details.contact_no }}<br>
<h3>Patient_BloodGroup:</h3>{{ appointment_details.BloodGroup }}<br>
<h3>Patient_Address:</h3>{{ appointment_details.Apt_Number }}, {{ appointment_details.Street_No }}, {{appointment_details.Street_Name }},
 {{appointment_details.City }},{{ appointment_details.State }}<br>
<h3>Appointment_Date:</h3>{{ appointment_details.appointment_date }}<br>
<h3>Appointment_Time:</h3>{{ appointment_details.appointment_time }}<br>
<h3>Appointment_Purpose:</h3>{{ appointment_details.appointment_purpose }}<br>
{% endblock %}

doctor/templates/doctor/registration_form.html
{% extends 'mainpage/base.html' %}
{% block title %} Doctor_registration{% load staticfiles %}{% endblock %}

{% block body %}
<div class = "container-fluid">
<div class = "row" style="margin-top:90px;">
    <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
            <div class="panel-body">
                <form class="form-horizontal" action="{% url 'doctor:doctor_register' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h2 class="text text-danger small">{{ error_message }}</h2>
                    {% include 'doctor/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

doctor/templates/doctor/set_schedule.html
{% extends 'doctor/base.html' %}
{% block title %} Hello doctor {% load staticfiles %}
{% endblock %}
{% block body %}
<style>
    .contact input[type="text"],
.contact input[type="date"],
.contact input[type="time"],
.contact input[type="radio"],
.contact textarea,
.contact button[type="submit"] {
  font: 400 12px/16px "Roboto", Helvetica, Arial, sans-serif;
}

.contact{
  background: #F9F9F9;
  padding: 25px;
  margin: 150px 0;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}

.contact h3 {
  display: block;
  font-size: 30px;
  font-weight: 300;
  margin-bottom: 10px;
}


fieldset {
  border: medium none !important;
  margin: 0 0 10px;
  min-width: 100%;
  padding: 0;
  width: 100%;
}

.contact input[type="text"],
.contact input[type="date"],
.contact input[type="time"],
.contact textarea {
  width: 100%;
  border: 1px solid #ccc;
  background: #FFF;
  margin: 0 0 5px;
  padding: 10px;
}

.contact input[type="text"]:hover,
.contact input[type="radio"]:hover,
.contact input[type="date"]:hover,
.contact input[type="time"]:hover,
.contact textarea:hover {
  -webkit-transition: border-color 0.3s ease-in-out;
  -moz-transition: border-color 0.3s ease-in-out;
  transition: border-color 0.3s ease-in-out;
  border: 1px solid #aaa;
}

.contact textarea {
  height: 100px;
  max-width: 100%;
  resize: none;
}

.contact button[type="submit"] {
  cursor: pointer;
  width: 100%;
  border: none;
  background: #4CAF50;
  color: #FFF;
  margin: 0 0 5px;
  padding: 10px;
  font-size: 15px;
}

.contact button[type="submit"]:hover {
  background: #43A047;
}

.contact button[type="submit"]:active {
  box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.5);
}

.contact input:focus,
.contact textarea:focus {
  outline: 0;
  border: 1px solid #aaa;
}

</style>
<div class="container2" style="margin-top:100px;">
  <form class="contact" action="{% url 'doctor:set' %}" method="post">
      {% csrf_token %}
    <h3>Set your schedule here:</h3>
    <fieldset>
      <input placeholder="Date" type="date" tabindex="1" name = "date" required autofocus>
    </fieldset>
    <fieldset>
      <input placeholder="Day" type="text" tabindex="2" name = "day" required>
    </fieldset>
    <fieldset>
      <input placeholder="Start_time" type="time" tabindex="3" name = "start_time" required>
    </fieldset>
    <fieldset>
      <input placeholder="End_Time" type="time" tabindex="4" name = "end_time" required>
    </fieldset>
      <fieldset>
          <label for="r2" class="control-label">Reserve this slot</label>
          <input type = "radio" name = "action" value = "book" id = "r2"><br>
          <label for="r1" class="control-label">Free this slot</label>
          <input type = "radio" name = "action" value = "free" id = "r1"><br>
      </fieldset>
    <fieldset>
      <textarea placeholder="Type your message here...." tabindex="5" name = "message" required></textarea>
    </fieldset>
    <fieldset>
      <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
    </fieldset>
  </form>
</div>
{% endblock %}

doctor/templates/doctor/simple.html
{% extends 'doctor/base.html' %}
{% block title %} Error!Doctor{%load staticfiles %}{% endblock %}

{% block body %}
<!--<div class="container" style = "margin-top:100px;">
    <h1> Sorry, but you have an appointment from {{ appointment.start_time }} to {{ appointment.end_time }} with {{ patient_details.username }}. Would you like
    to reschedule the appointment or cancel it:</h1><br>
    <form action = "{% url 'doctor:check' %}" method = "post">
        <input type = "radio" name = "check" value="reschedule">Reschedule<br>
        <input type = "radio" name = "check" value="cancel">Cancel<br>
        <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
    </form>

</div>-->

<div class="container container_top">
{% for uid,i,z in appts %}
    <div class="shc_{{uid}} abcd">
        <h4 style="color:blue;"> Sorry, but you have an appointment from {{ i.start_time }} to {{ i.end_time }}</h4>
    <h5 style="color:blue;">Would you like to reschedule the appointment or cancel it
      <a href = "{% url 'doctor:appointmentdetails' i.appointment_id %}"> Appointment Details </a>
      :</h5><br>
    <button class="btn btn-success reschedule" s="{{ i.start_time }}" e="{{ i.end_time }}" d="{{ i.date }}" \
            doctorid="{{ i.doctor_id }}" u="{{ uid }}">Reschedule</button>
    <button class="btn btn-success cancel" s="{{ i.start_time }}" e="{{ i.end_time }}" d="{{ i.date }}" \
            doctorid="{{ i.doctor_id }}" u="{{ uid }}">Cancel</button>
        </div>
{% endfor %}
{% for uid,i in other_appts %}
    <div class="shc_{{uid}} abcd">
        <h4 style="color:blue;"> Sorry, but you have a schedule from {{ i.start_time }} to {{ i.end_time }} for {{ i.message }}</h4>
    <h5 style="color:blue;">Would you like to reschedule or cancel it:</h5><br>
    <button class="btn btn-success reschedule" s="{{ i.start_time }}" e="{{ i.end_time }}" d="{{ i.date }}" \
            doctorid="{{ i.doctor_id }}" u="{{ uid }}">Reschedule</button>
    <button class="btn btn-success cancel" s="{{ i.start_time }}" e="{{ i.end_time }}" d="{{ i.date }}" \
            doctorid="{{ i.doctor_id }}" u="{{ uid }}">Cancel</button>
        </div>
{% endfor %}
<h1> Examinations:</h1>
{% for uid,i,z in examinations %}
    <div class="shc_{{uid}} abcd">
        <h4 style="color:blue;"> Sorry, but you have an examination scheduled from {{ i.start_time }} to {{ i.end_time }} for patient {{ z.first_name }} {{ z.last_name }}</h4>
    <h5 style="color:blue;">Would you like to reschedule or cancel it:</h5><br>
        <!--z containes all the columns of auth_user and patient-->
    <button class="btn btn-success reschedule" s="{{ i.start_time }}" e="{{ i.end_time }}" d="{{ i.examination_date }}" \
            doctorid="{{ i.doctor_id }}" u="{{ uid }}">Reschedule</button>
    <button class="btn btn-success cancel" s="{{ i.start_time }}" e="{{ i.end_time }}" d="{{ i.examination_date }}" \
            doctorid="{{ i.doctor_id }}" u="{{ uid }}">Cancel</button>
        </div>
{% endfor %}
</div>
<style>
    .modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;
    margin: 15% auto; /* 15% from the top and centered */
    padding: 20px;
    border: 1px solid #888;
    width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button */
.close {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
}
</style>
<div id="myModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>

         <form method="post" onsubmit="return formvalid();" id="reschedule_form">
            {% csrf_token %}
            <input class="starttime" type = "time" name="starttime" id="starttime">
            <label for="starttime">Start Time</label><br>
            <input class="endtime" type = "time" name = "endtime" id="endtime">
            <label for="endtime">End Time</label><br>
            <input class="date" type="date" name = "date" id ="date">
            <label for="date">Date</label><br>
            <input class="starttime_old" name="starttime_old" disabled="true">
            <label for="starttime_old">Earlier Start Time</label><br>
             <input class="endtime_old" name = "endtime_old" disabled="true">
             <label for="endtime_old">Earlier End Time</label><br>
            <input class="date_old" name = "date_old" disabled="true">
            <label for="date_old">Earlier Date</label><br>
            <input class="doctor_id" name = "doctor_id" hidden disabled="true">

            <input class="uid" hidden disabled="true">
            <input type="submit" id="submitreschedule">
         </form>
    </div>


</div>

<button id="openmodal" hidden></button>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    var btn = document.getElementById("openmodal");
    var modal = document.getElementById("myModal");
    var span = document.getElementsByClassName("close")[0];
    btn.onclick = function() {
        modal.style.display = "block";
    }

    span.onclick = function() {
        modal.style.display = "none";
    }

    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
    $('.reschedule').click(function(){
        $('#openmodal').click();
        $(".starttime_old").val($(this).attr('s'));
        $(".endtime_old").val($(this).attr('e'));
        $(".date_old").val($(this).attr('d'));
        $(".doctor_id").val($(this).attr('doctorid'));
        $(".uid").val($(this).attr('u'));

    });
    function formvalid(){
        // if($('.starttime').val()==""){
        // }
        return false;
    }
    
    
    
</script>
<script type="text/javascript">
    function redirect(){
        //alert($('.abcd:visible'.length));
        if($('.abcd:visible').length<1){
            $.ajax({
            type:"POST",
            url:"{% url 'doctor:set_2' %}",
            data:{"csrfmiddlewaretoken":"{{csrf_token}}","date":"{{ date }}","day":"{{ day }}","start_time":"{{ start_time }}","end_time":"{{ end_time }}","action":"{{ action }}","message":"{{ message }}","doctor_id":"{{ doctor_id }}"},
        }).done(function(request){
            window.location.href="{% url 'doctor:index' %}";

        }).fail(function(){

        });
            
        }
        alert($('.abcd:visible').length);
    }
    $('#submitreschedule').click(function(){
        //alert('input called');
        $.ajax({
            type:"POST",
            url:"{% url 'doctor:check' %}",
            data:{"start_time":$(".starttime").val(),"end_time":$(".endtime").val(),"date":$(".date").val(),"starttime_old":$(".starttime_old").val(),"endtime_old":$(".endtime_old").val(),"date_old":$(".date_old").val(),"doctor_id":$(".doctor_id").val(),"csrfmiddlewaretoken":"{{csrf_token}}"},
        }).done(function(request){
            if(request.clash=='1'){
                alert('sorry this time slot is also reserved');
            }
            else{
                //alert($('.uid').val());
                span.click();
                $('.shc_'+$('.uid').val()).hide();
                redirect();
            }
            /*alert($('.uid').val());
            alert(request.clash);*/
        }).fail(function(){

        });
    });
</script>
<script>
    
    $('.cancel').click(function(){
        //alert();
        var v = $(this).attr('u');
        $.ajax({
            type:"POST",
            url:"{% url 'doctor:cancel' %}",
            data:{"s":$(this).attr('s'),"e":$(this).attr('e'),"d":$(this).attr('d'),"doctor_id":$(this).attr('doctorid'),"csrfmiddlewaretoken":"{{csrf_token}}"},
        }).done(function(request){
            $('.shc_' + v).hide();
            redirect();
        }).fail(function(){

        });
    });
</script>
<script type="text/javascript">

        function res() {
            var m=$('nav').height()+50;
        $('.container_top').attr('style','padding-top:'+ m +'px;');
        }
     $(window).resize(function(){
        res();
    });
     res();
</script>
{% endblock %}