doctor/urls.py
from django.conf.urls import url
from . import views

app_name = 'doctor'
urlpatterns = [
    #url(r'^(?P<doctor_id>[0-9]+)/$',views.index,name='index'),
    url(r'^home/$', views.index, name='index'),
    url(r'^register/$', views.DoctorFormView.as_view(), name='doctor_register'),
    url(r'^logout/$',views.Logout,name='logout'),
    url(r'^set_schedule/$',views.Set,name = 'set'),
    url(r'^set2/$',views.set_2,name="set_2"),
    url(r'^check/$',views.check,name='check'),
    url(r'^cancel/$',views.cancel,name='cancel'),
    url(r'^checkappointment/(?P<appointment_id>[0-9]+)/$',views.appointment_details,name='appointmentdetails'),
    #check_appointments
    #specify_schedule
    #See reports of patients
]

hospital/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/',include('mainpage.urls', namespace='mainpage')),
    url(r'^(/)?$',RedirectView.as_view(url='/home/')),
    url(r'^services/',include('services.urls',namespace='services')),
    url(r'^login/',RedirectView.as_view(url='/home/login/')),
    url(r'^doctor/',include('doctor.urls',namespace='doctor')),
    url(r'^patient/',include('patient.urls',namespace='patient')),
    url(r'^manager/',include('manager.urls',namespace='manager')),
]

#if settings.DEBUG:
#    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
#    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mainpage/urls.py
from django.conf.urls import include,url
from . import views

app_name = 'mainpage'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^AboutUs/',views.aboutus, name = 'aboutus'),
    url(r'^login/$',views.Login,name='login'),
    url(r'^logout/$',views.Logout,name='logout'),
    url(r'^register/$',views.register,name='register'),
    url(r'^check_registration/$',views.check,name='check_registration'),
    url(r'^bookappointment/$',views.book_appointment,name='bookappointment'),
    #url('^appointment_details/id',views.appointment_details,name='appointmentdetails'),
    url(r'^doctordetails/(?P<doctor_id>[0-9]+)/$',views.doctordetails,name='doctordetails'),
]

services/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'services'

urlpatterns=[
    url(r'^$',views.allservices,name='allservices'),
    url(r'(?P<lab_id>[0-9]+)/$',views.lab_details, name = 'lab_details'),
    url(r'rooms/$',views.rooms,name='rooms'),

]

mainpage/models.py
from django.contrib.auth.models import User,AbstractUser,Group
from django.db import models
from django.contrib import admin


# Create your models here.

services/models.py
from django.db import models

# Create your models here.

mainpage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.contrib.auth import authenticate,logout,login
from django.contrib.auth.models import User,Group
from django.db import connection,transaction

# Create your views here.
def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def index(request):
    template = loader.get_template('mainpage/startpage.html')
    #if request.user.is_authenticated:
    #   return HttpResponse(template.render({},request))
    #cursor.execute('CREATE TABLE IF NOT EXISTS User(ID INT PRIMARY KEY,Username VARCHAR(100) NOT NULL UNIQUE,'
    #               'Password VARCHAR(100) NOT NULL UNIQUE, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100), '
    #               'email  VARCHAR(100))')
    with connection.cursor() as cursor:
        
        cursor.execute('CREATE TABLE IF NOT EXISTS doctorspeciality(label varchar(10) primary key,speciality varchar(30) not null)')
        cursor.execute('CREATE TABLE IF NOT EXISTS lab(lab_id INTEGER PRIMARY KEY AUTO_INCREMENT,lab_name VARCHAR(100),lab_open_time time, lab_close_time time,no_doctors INT DEFAULT 0,no_workers INT DEFAULT 0)')
        cursor.execute('CREATE TABLE IF NOT EXISTS services(service_id INTEGER PRIMARY KEY AUTO_INCREMENT, service_name VARCHAR(100), service_details TEXT)')
        cursor.execute('CREATE TABLE IF NOT EXISTS room(room_id INTEGER PRIMARY KEY AUTO_INCREMENT,Floor Int, Type VARCHAR(100), Cost_Per_Day FLOAT, room_details TEXT)')

        cursor.execute('INSERT INTO lab(lab_name,lab_open_time,lab_close_time) SELECT * FROM ( SELECT "Operation Theatre","8:00","22:00") AS TMP'
                       ' WHERE NOT EXISTS(SELECT lab_name,lab_open_time,lab_close_time FROM lab WHERE lab_id=1) LIMIT 1;')
        cursor.execute('INSERT INTO lab(lab_name,lab_open_time,lab_close_time) SELECT * FROM ( SELECT "CT SCAN","10:00","22:00") AS TMP'
                       ' WHERE NOT EXISTS(SELECT lab_name,lab_open_time,lab_close_time FROM lab WHERE lab_id=2) LIMIT 1;')
        cursor.execute('CREATE TABLE IF NOT EXISTS doctor(doctor_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, user_id int NOT NULL, speciality varchar(10),'
                      'degree VARCHAR(30), Street_no VARCHAR(10), Street_Name VARCHAR(100),lab INT,'
                       'Apt_Number VARCHAR(10),City VARCHAR(20), State VARCHAR(20), Zip_code VARCHAR(10), Gender CHAR(1),Work_Duration VARCHAR(10),'
                       'Account_No VARCHAR(20) NOT NULL, foreign key(speciality) references doctorspeciality(label), '
                       'foreign key (user_id) REFERENCES auth_user(id),foreign key(lab) REFERENCES lab(lab_id))')
        cursor.execute('CREATE TABLE IF NOT EXISTS doctor_phone(doctor_id INT,contact VARCHAR(13),foreign key(doctor_id) references doctor(doctor_id),primary key(doctor_id,contact))')
        cursor.execute('INSERT INTO doctorspeciality SELECT * FROM ( SELECT "GYN","Gynaeocologist") AS TMP'
                       ' WHERE NOT EXISTS(SELECT * FROM doctorspeciality WHERE label="GYN") LIMIT 1;')
        cursor.execute('INSERT INTO doctorspeciality SELECT * FROM ( SELECT "PAED","Padaetrician") AS TMP'
                       ' WHERE NOT EXISTS(SELECT * FROM doctorspeciality WHERE label="PAED") LIMIT 1;')
        cursor.execute('INSERT INTO doctorspeciality SELECT * FROM ( SELECT "PATH","Pathologist") AS TMP'
                        ' WHERE NOT EXISTS(SELECT * FROM doctorspeciality WHERE label="PATH") LIMIT 1;')
        cursor.execute('CREATE TABLE IF NOT EXISTS unregistered_patients(email varchar(100) primary key,'
                           'username varchar(100) not null, dob date, contact varchar(13),address varchar(100), street varchar(50),'
                           'city varchar(20),zip_code varchar(6))')
        cursor.execute('CREATE TABLE IF NOT EXISTS unregisteredappointments(appointment_id INTEGER primary key AUTO_INCREMENT,'
                           'patient varchar(100),appointment_date date,appointment_time time,department varchar(100), '
                            'appointment_purpose varchar(100),doctor_id int,foreign key(doctor_id) references doctor(doctor_id),'
                            'foreign key(patient) references unregistered_patients(email))')
        cursor.execute('CREATE TABLE IF NOT EXISTS patients(patient_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, user_id int NOT NULL, type varchar(10),'
                      'DOB date,BloodGroup Varchar(5),Job VARCHAR(20),Street_no VARCHAR(10), Street_Name VARCHAR(100),'
                       'Apt_Number VARCHAR(10),City VARCHAR(20), State VARCHAR(20), Zip_code VARCHAR(10), Gender CHAR(1),'
                       'Account_No VARCHAR(20) NOT NULL, foreign key (user_id) REFERENCES auth_user(id))')
        #AadharCardNo for Patient
        cursor.execute('CREATE TABLE IF NOT EXISTS patient_phone(patient_id INT,contact VARCHAR(13), foreign key(patient_id) references patients(patient_id),primary key(patient_id,contact))')

        cursor.execute('CREATE TABLE IF NOT EXISTS room_booked(room_id INT, patient_id INT, foreign key(room_id) REFERENCES room(room_id), foreign key(patient_id) REFERENCES patients(patient_id),primary key(room_id,patient_id))')
        cursor.execute('CREATE TABLE IF NOT EXISTS registeredappointments(id INTEGER PRIMARY KEY AUTO_INCREMENT,patient_id INT, '
                       'appointment_date date,appointment_time time,department varchar(100),appointment_purpose varchar(100),'
                       'doctor_id int,foreign key(doctor_id) references doctor(doctor_id),'
                            'foreign key(patient_id) references patients(patient_id))')
        cursor.execute('CREATE TABLE IF NOT EXISTS appointments(id INTEGER PRIMARY KEY AUTO_INCREMENT, unregistered_id INTEGER, registered_id INTEGER, is_registered bool, foreign key(unregistered_id) references unregisteredappointments(appointment_id), '
                       'foreign key(registered_id) references registeredappointments(id))')
        cursor.execute("create table if not exists schedule(start_time time not null,end_time time not null, date date not null,day char(100),message char(200),doctor_id int,is_appointment boolean default 0,is_examination boolean default 0, appointment_id int, foreign key(appointment_id) references appointments(id),foreign key(doctor_id) references doctor(doctor_id),primary key(doctor_id,date,start_time,end_time))")
        cursor.execute("CREATE TABLE IF NOT EXISTS notifications(notification_id INTEGER PRIMARY KEY AUTO_INCREMENT, notification_message TEXT,patient_id INT NOT NULL,FOREIGN KEY(patient_id) REFERENCES patients(patient_id));")
        cursor.execute("CREATE TABLE IF NOT EXISTS diseases(disease_id INTEGER PRIMARY KEY AUTO_INCREMENT, disease_name text)")
        cursor.execute("CREATE TABLE IF NOT EXISTS examination(examination_date date NOT NULL, examination_type VARCHAR(100) NOT NULL,start_time time NOT NULL,end_time time NOT NULL, "
                       "patient_id int NOT NULL, doctor_id INT NOT NULL, disease int, Outcome text, Treatment text,lab int, is_done boolean, foreign key(lab) references lab(lab_id), "
                       " foreign key(patient_id) references patients(patient_id) "
                       ", foreign key(doctor_id) references doctor(doctor_id),foreign key(disease) references diseases(disease_id), PRIMARY KEY(examination_date,examination_type,start_time,end_time,patient_id,doctor_id))")
        
        cursor.execute('CREATE TABLE IF NOT EXISTS managers(user_id INT, foreign key(user_id) REFERENCES auth_user(id),primary key(user_id))')
        #How to add constraint for schedule to be a foreign key of examination
        #How to create weak entity with another weak entity.
        cursor.execute("CREATE TABLE IF NOT EXISTS history(id INTEGER PRIMARY KEY AUTO_INCREMENT,disease INT NOT NULL, details TEXT, start_date date, end_date date, patient_id INT NOT NULL,"
                       "foreign key(disease) REFERENCES diseases(disease_id), foreign key(patient_id) references patients(patient_id) )")

        cursor.execute('CREATE TABLE IF NOT EXISTS medicine(medicine_id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,name VARCHAR(30) NOT NULL)')
        cursor.execute('CREATE TABLE IF NOT EXISTS medicine_details(Invoice_No VARCHAR(10) NOT NULL, medicine_name INT, Batch_No VARCHAR(10), Date_of_Manufacture date,Date_of_Expiry date, Price float NOT NULL,Quantity INT, foreign key(medicine_name) references medicine(medicine_id))')
        cursor.execute('CREATE TABLE IF NOT EXISTS instrument(instrument_id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, instrument_name VARCHAR(50),cost_per_piece float NOT NULL, instrument_type VARCHAR(20))')
        cursor.execute('CREATE TABLE IF NOT EXISTS purchase_details(instrument_id INTEGER, date_of_purchase date,count_bought INT, place_of_purchase VARCHAR(100), foreign key(instrument_id) references instrument(instrument_id),primary key(instrument_id,date_of_purchase,count_bought,place_of_purchase))')
        cursor.execute('CREATE TABLE IF NOT EXISTS worker(worker_id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, worker_name VARCHAR(50),worker_type VARCHAR(10),salary float,date_of_joining date,qualifications VARCHAR(100),street_no varchar(10),street_name varchar(20),apt_number varchar(10),city varchar(20),state varchar(20),gender varchar(20),account_no varchar(20),work_duration varchar(20))')
        cursor.execute('CREATE TABLE IF NOT EXISTS worker_phone(worker_id INTEGER NOT NULL,phone VARCHAR(13),foreign key(worker_id) references worker(worker_id), primary key(worker_id,phone))')

services/views.py
from django.shortcuts import render
from django.db import connection,transaction

# Create your views here.
def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def allservices(request):
	cursor = connection.cursor()
	cursor.execute('SELECT * FROM lab')
	lab_details = dictfetchall(cursor)
	cursor.execute('SELECT * from services')
	service_details = dictfetchall(cursor)
	print(lab_details,service_details)
	context = {'labs':lab_details,'services':service_details}
	return render(request,'services/services.html',context)

def lab_details(request,lab_id):
	cursor = connection.cursor()
	cursor.execute('SELECT * from lab where lab_id=%s',[lab_id])
	lab_details = dictfetchall(cursor)
	print(lab_details)
	context = {'lab': lab_details[0],}
	return render(request,'services/lab_details.html',context)

def rooms(request):
	cursor = connection.cursor()
	cursor.execute('SELECT DISTINCT Type from room')
	types = dictfetchall(cursor)
	context={'types':types,}
	return render(request,'services/services.html',context)

mainpage/templates/mainpage/Thank_you.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Thank you your appointment has been booked at {{ appointment_time }} + " with doctor <a href = "{% url 'mainpage:aboutus' %}"> {{ name.username }} </a>. Return to the <a href = "{% url 'mainpage:index' %}"> Homepage here</a>.
</body>
</html>

mainpage/templates/mainpage/about-us.html
{% extends 'mainpage/base.html' %}
{% block title %} Meet Our Doctors {% load staticfiles %}{% endblock %}
{% block body %}
<section id="meetDoctors">
<div class="col-lg-12 col-md-12">
    <div class="section-heading">
        <h2>Meet Our Doctors</h2>
        <hr class="line">
    </div>

<div class="row">
{% for i in doctors %}
  <div class="column">
    <div class="card">
    <figure>
      <img src="{% static 'images/doctor-1.jpg' %}" alt="Jane" style="width:70%;height:70%">
      <div class="container" style="color:blue;">
        <h2>Dr. {{ i.first_name }} {{ i.last_name }}</h2>
        <p class="title">Doctor &amp; {{ i.degree }}</p>
        <p>{{ i.speciality }}</p>
        <p>{{ i.email }}</p>
        <p style="color:red;">Lab:<a href="{% url 'services:lab_details' i.lab_id %}">  <button class="button" style="width:50%; padding-right:20%;">{{ i.lab_name }}</button></a></p>
        <p><button class="button">{{ i.contact }}</button></p>
        <a href="{% url 'mainpage:doctordetails' i.doctor_id %}"><button type="button" class="btn btn-outline-info">View</button></a>
      </div>
      </figure>
    </div>
  </div>
{% endfor %}
</div>
</div>
</section>
{% endblock %}

mainpage/templates/mainpage/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}  {% endblock %}</title>
    {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">

</head>
<body>
<!--<div id="preloader">
      <div id="status">&nbsp;</div>
</div>-->
<a class="scrollToTop" href="#"><i class="fa fa-heartbeat"></i></a>

{% block navbar %}

<nav class = "navbar navbar-default navbar-fixed-top" role="navigation">
  <div class = "container">
  <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNavbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'mainpage:index' %}">CNH</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right main-nav" id="topmenu" >
        {% ifequal user_type 0 %}
          <li class="active"><a href="{% url 'doctor:index' %}"> Doctor_Home </a></li>
        {% endifequal %}
        {% ifequal user_type 1 %}
          <li class="active"><a href="{% url 'patient:index' %}"> Patient_Home </a></li>
        {% endifequal %}
        {% ifequal user_type 2 %}
          <li class="active"><a href="{% url 'manager:index' %}"> Manager_Home </a></li>
        {% endifequal %}
        <li class="active"><a href="{% url 'mainpage:index' %}"> Home </a></li>
        <li ><a href="{% url 'mainpage:aboutus' %}">About Us</a></li>
        <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Services <span class="fa fa-angle-down"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'services:allservices' %}">All Services</a></li>
                    {% for i in service_details %}
                    <li><a href="{% url 'services:allservices' %}">{{ i.service_name }}</a></li>
                    {% endfor %}
                    {% for i in lab_details %}
                    <li><a href="{% url 'services:lab_details' i.lab_id %}"> {{ i.lab_name }}</a></li>
                    {% endfor %}
                  </ul>
                </li>
        {% if request.user.is_authenticated %}
          <li ><a href="{% url 'mainpage:logout' %}">Logout</a></li>
        {% else %}
          <li ><a href="{% url 'mainpage:login' %}">Login</a></li>
        {% endif %}
        {% ifequal user_type -1 %}
        {% url 'mainpage:index' as about %}
          <li > {% ifequal request.path about %}
            <a data-toggle="modal" data-target="#myModal" href="" data-hover="Appointment"><span> Book Appointment</span></a>
          {% else %}
            <a href="{% url 'mainpage:index' %}"><span>Book Appointment</span></a>
          {% endifequal %}
          </li>
        {% endifequal %}
        {% ifequal user_type 1 %}
          <li >
            <a href="{% url 'patient:index' %}" data-hover="Appointment"><span> Book Appointment</span></a>
          </li>
        {% endifequal %}
        <li > <a href = "#"> Contact </a></li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}
{% block body %}

{% endblock %}

 <footer id="footer">
      <!-- Start Footer Top -->
      <div class="footer-top">
        <div class="container">
          <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-3">
              <div class="single-footer-widget">
                <div class="section-heading">
                <h2>About Us</h2>
                <hr class="line">
              </div>
              <p>--------------------------------------------------------------- -------------------- --------- - - - - - - - </p>
              </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3">
              <div class="single-footer-widget">
              <div class="links">

              <ul class="footer-service">
                <li><a href="#"><span class="fa fa-check"></span>Home</a></li>
                <li><a href="#"><span class="fa fa-check"></span>Contact Us</a></li>
                <li><a href="#"><span class="fa fa-check"></span>Services</a></li>
                <li><a href="#"><span class="fa fa-check"></span>FAQ</a></li>
              </ul>
              </div>
              </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3">
              <div class="single-footer-widget">
                <div class="section-heading">
                <h2>Social Media</h2>
                <div class="line"></div>
              </div>
                <div id="socialMedia" class="span3 pull-right">
                  <h5>SOCIAL MEDIA </h5>
                  <a href="#"><img width="60" height="60" src="{% static 'images/facebook.png' %}" title="facebook" alt="facebook"/></a>
                  <a href="#"><img width="60" height="60" src="{% static 'images/twitter.png' %}" title="twitter" alt="twitter"/></a>
                  <a href="#"><img width="60" height="60" src="{% static 'images/youtube.png' %}" title="youtube" alt="youtube"/></a>
                </div>
              </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3">
              <div class="single-footer-widget">
                <div class="section-heading">
                <h2>Contact Info</h2>
                <div class="line"></div>
              </div>
              <p>Our contact details are:</p>
              <address class="contact-info">
                <p><span class="fa fa-home"></span>Chirag Nursing Home, Opp. Balaji Mandir, Banbata Ganj, Moradabad, U.P., India</p>
                <p><span class="fa fa-phone"></span>7599292732</p>
                <p><span class="fa fa-envelope"></span>adit.agarwal.cse15@itbhu.ac.in</p>
              </address>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Start Footer Middle -->
      <div class="footer-middle">
        <div class="container">
          <div class="row">
          <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="footer-copyright">
              <p>&copy; Copyright 2015 <a href="{% url 'mainpage:index' %}">Chirag Nursing Home</a></p>
            </div>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="footer-social">
                <a href="#"><span class="fa fa-facebook-square"></span></a>
                <a href="#"><span class="fa fa-twitter-square"></span></a>
                <a href="#"><span class="fa fa-google-plus"></span></a>
                <a href="#"><span class="fa fa-linkedin"></span></a>
            </div>
          </div>
        </div>
        </div>
      </div>
    </footer>
</body>
</html>

mainpage/templates/mainpage/doctor_detail.html
{% extends 'mainpage/base.html' %}
{% block title %} Meet Our Doctors {% load staticfiles %}{% endblock %}
{% block body %}
<section id="meetDoctors">
<div class="col-lg-12 col-md-12">
    <div class="section-heading">
        <h2>Meet Our Doctors</h2>
        <hr class="line">
    </div>

<div class="row">
  <div class="column">
    <div class="card">
    <figure>
      <img src="{% static 'images/doctor-1.jpg' %}" alt="Jane" style="width:70%;height:70%">
      <div class="container" style="color:blue;">
        <h2>Dr. {{ i.first_name }} {{ i.last_name }}</h2>
        <p class="title">Doctor &amp; {{ i.degree }}</p>
        <p>{{ i.speciality }}</p>
        <p>{{i.degree}}</p>
        <p>{{ i.email }}</p>
        <p>{{ i.Gender }}</p>
        <p>{{ i.Work_Duration }}</p>
        <p>{{i.Apt_Number}},{{i.Street_no}},{{i.Street_Name}},{{i.City}},{{i.State}}</p>
        <p style="color:red;">Lab:<a href="{% url 'services:lab_details' i.lab_id %}">  <button class="button" style="width:50%; padding-right:20%;">{{ i.lab_name }}</button></a></p>
        <p><button class="button">{{ i.contact }}</button></p>
      </div>
      </figure>
    </div>
  </div>
</div>
</div>
</section>
{% endblock %}

mainpage/templates/mainpage/login.html
{% extends 'mainpage/base.html' %}

{% block title %} Login Page {% endblock %}
{% block body %}

<div class="container">
			<div class="row main">
				<div class="panel-heading">
	               <div class="panel-title text-center">
	               		<h1 class="title">Login Here</h1>
	               		<hr />
	               	</div>
	            </div> 
				<div class="main-login main-center">
					<form class="form-horizontal" method="post" action="{% url 'mainpage:login' %}">
						{% csrf_token %}
						<div class="form-group">
							<label for="username" class="cols-sm-2 control-label">Username</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-users fa" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="username" id="username"  placeholder="Enter your Username"/>
								</div>
							</div>
						</div>

						<div class="form-group">
							<label for="password" class="cols-sm-2 control-label">Password</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
									<input type="password" class="form-control" name="password" id="password"  placeholder="Enter your Password"/>
								</div>
							</div>
						</div>

						<div class="form-group ">
							<button type="submit" class="btn btn-primary btn-lg btn-block login-button">Login</button>
						</div>
                        <div class = "form-group">
                            <a href="{% url 'mainpage:register' %}"><button type="button" class = "btn btn-primary btn-lg btn-block">Register</button></a>
                        </div>
					</form>
				</div>
			</div>
		</div>
{% endblock %}

mainpage/templates/mainpage/register_choose.html
{% extends 'mainpage/base.html' %}
{% block title %} Register {% endblock %}
{% block body %}

    <div class="container">
			<div class="row main">
				<div class="panel-heading">
	               <div class="panel-title text-center">
	               		<h1 class="title">Choose Your Registration:</h1>
	               		<hr />
	               	</div>
	            </div>
				<div class="main-login main-center" style="margin: 0 auto;">
					<form class="form-horizontal" method="post" action="{% url 'mainpage:check_registration' %}">
						{% csrf_token %}

						<div class="form-group" style="margin: 0 auto;">
							<div class="cols-sm-10">
								<div class="input-group" style="align:center;">
									<input type="radio" class="form-control" name="type" id="doctor" value="doctor"/>
                                    <label for ="doctor" style="color:black;float:right;">Register as doctor </label><br>
                                    <input type="radio" class="form-control" name="type" id="patient" value="patient"/>
                                    <label for ="patient" style="color:black;float:right;">Register as patient</label><br>
								</div>
							</div>
						</div>

						<div class="form-group ">
							<button type="submit" class="btn btn-primary btn-lg btn-block login-button">Submit</button>
						</div>
					</form>
				</div>
			</div>
		</div>


{% endblock %}