doctor/urls.py
from django.conf.urls import url
from . import views

app_name = 'doctor'
urlpatterns = [
    #url(r'^(?P<doctor_id>[0-9]+)/$',views.index,name='index'),
    url(r'^home/$', views.index, name='index'),
    url(r'^register/$', views.DoctorFormView.as_view(), name='doctor_register'),
    url(r'^logout/$',views.Logout,name='logout'),
    url(r'^set_schedule/$',views.Set,name = 'set'),
    url(r'^set2/$',views.set_2,name="set_2"),
    url(r'^check/$',views.check,name='check'),
    url(r'^cancel/$',views.cancel,name='cancel'),
    url(r'^checkappointment/(?P<appointment_id>[0-9]+)/$',views.appointment_details,name='appointmentdetails'),
    #check_appointments
    #specify_schedule
    #See reports of patients
]

hospital/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/',include('mainpage.urls', namespace='mainpage')),
    url(r'^(/)?$',RedirectView.as_view(url='/home/')),
    url(r'^services/',include('services.urls',namespace='services')),
    url(r'^login/',RedirectView.as_view(url='/home/login/')),
    url(r'^doctor/',include('doctor.urls',namespace='doctor')),
    url(r'^patient/',include('patient.urls',namespace='patient')),
    url(r'^manager/',include('manager.urls',namespace='manager')),
]

#if settings.DEBUG:
#    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
#    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mainpage/urls.py
from django.conf.urls import include,url
from . import views

app_name = 'mainpage'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^AboutUs/',views.aboutus, name = 'aboutus'),
    url(r'^login/$',views.Login,name='login'),
    url(r'^logout/$',views.Logout,name='logout'),
    url(r'^register/$',views.register,name='register'),
    url(r'^check_registration/$',views.check,name='check_registration'),
    url(r'^bookappointment/$',views.book_appointment,name='bookappointment'),
    #url('^appointment_details/id',views.appointment_details,name='appointmentdetails'),
    url(r'^doctordetails/(?P<doctor_id>[0-9]+)/$',views.doctordetails,name='doctordetails'),
]

services/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'services'

urlpatterns=[
    url(r'^$',views.allservices,name='allservices'),
    url(r'(?P<lab_id>[0-9]+)/$',views.lab_details, name = 'lab_details'),
    url(r'rooms/$',views.rooms,name='rooms'),

]

services/models.py
from django.db import models

# Create your models here.

services/views.py
from django.shortcuts import render
from django.db import connection,transaction

# Create your views here.
def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def allservices(request):
	cursor = connection.cursor()
	cursor.execute('SELECT * FROM lab')
	lab_details = dictfetchall(cursor)
	cursor.execute('SELECT * from services')
	service_details = dictfetchall(cursor)
	print(lab_details,service_details)
	context = {'labs':lab_details,'services':service_details}
	return render(request,'services/services.html',context)

def lab_details(request,lab_id):
	cursor = connection.cursor()
	cursor.execute('SELECT * from lab where lab_id=%s',[lab_id])
	lab_details = dictfetchall(cursor)
	print(lab_details)
	context = {'lab': lab_details[0],}
	return render(request,'services/lab_details.html',context)

def rooms(request):
	cursor = connection.cursor()
	cursor.execute('SELECT DISTINCT Type from room')
	types = dictfetchall(cursor)
	context={'types':types,}
	return render(request,'services/services.html',context)

services/templates/services/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}  {% endblock %}</title>
    {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">

</head>
<body>
<!--<div id="preloader">
      <div id="status">&nbsp;</div>
</div>-->
<a class="scrollToTop" href="#"><i class="fa fa-heartbeat"></i></a>

{% block navbar %}

<nav class = "navbar navbar-default navbar-fixed-top" role="navigation">
  <div class = "container">
  <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNavbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'mainpage:index' %}">CNH</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right main-nav" id="topmenu" >
        <li class="active"><a href="{% url 'mainpage:index' %}"> Home </a></li>
        <li><a href="{% url 'mainpage:aboutus' %}">About Us</a></li>
        <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Services <span class="fa fa-angle-down"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'services:allservices' %}">Medical Counseling</a></li>
                    <li><a href="{% url 'services:allservices' %}">Operations</a></li>
                    <li><a href="{% url 'services:allservices' %}">Pregnancy Care</a></li>
                  </ul>
                </li>
        <li><a href="{% url 'mainpage:login' %}">Login</a></li>
        <li> <a data-toggle="modal" data-target="#myModal" href="#" data-hover="Appointment"><span> Book Appointment</span></a></li>
        <li> <a href = "#"> Contact </a></li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}
{% block body %}

{% endblock %}

 <footer id="footer">
      <!-- Start Footer Top -->
      <div class="footer-top">
        <div class="container">
          <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-3">
              <div class="single-footer-widget">
                <div class="section-heading">
                <h2>About Us</h2>
                <hr class="line">
              </div>
              <p>--------------------------------------------------------------- -------------------- --------- - - - - - - - </p>
              </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3">
              <div class="single-footer-widget">
              <div class="links">

              <ul class="footer-service">
                <li><a href="#"><span class="fa fa-check"></span>Home</a></li>
                <li><a href="#"><span class="fa fa-check"></span>Contact Us</a></li>
                <li><a href="#"><span class="fa fa-check"></span>Services</a></li>
                <li><a href="#"><span class="fa fa-check"></span>FAQ</a></li>
              </ul>
              </div>
              </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3">
              <div class="single-footer-widget">
                <div class="section-heading">
                <h2>Social Media</h2>
                <div class="line"></div>
              </div>
                <div id="socialMedia" class="span3 pull-right">
                  <h5>SOCIAL MEDIA </h5>
                  <a href="#"><img width="60" height="60" src="{% static 'images/facebook.png' %}" title="facebook" alt="facebook"/></a>
                  <a href="#"><img width="60" height="60" src="{% static 'images/twitter.png' %}" title="twitter" alt="twitter"/></a>
                  <a href="#"><img width="60" height="60" src="{% static 'images/youtube.png' %}" title="youtube" alt="youtube"/></a>
                </div>
              </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3">
              <div class="single-footer-widget">
                <div class="section-heading">
                <h2>Contact Info</h2>
                <div class="line"></div>
              </div>
              <p>Our contact details are:</p>
              <address class="contact-info">
                <p><span class="fa fa-home"></span>Chirag Nursing Home, Opp. Balaji Mandir, Banbata Ganj, Moradabad, U.P., India</p>
                <p><span class="fa fa-phone"></span>7599292732</p>
                <p><span class="fa fa-envelope"></span>adit.agarwal.cse15@itbhu.ac.in</p>
              </address>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Start Footer Middle -->
      <div class="footer-middle">
        <div class="container">
          <div class="row">
          <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="footer-copyright">
              <p>&copy; Copyright 2015 <a href="{% url 'mainpage:index' %}">Chirag Nursing Home</a></p>
            </div>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="footer-social">
                <a href="#"><span class="fa fa-facebook-square"></span></a>
                <a href="#"><span class="fa fa-twitter-square"></span></a>
                <a href="#"><span class="fa fa-google-plus"></span></a>
                <a href="#"><span class="fa fa-linkedin"></span></a>
            </div>
          </div>
        </div>
        </div>
      </div>
    </footer>
</body>
</html>

services/templates/services/lab_details.html
{% extends 'mainpage/base.html' %}
{% block title %} Our Services {% load staticfiles %}{% endblock %}
{% block body %}

<section class="service">
  <div class="container">
    <div class="row">
    	<p style="color:blue;">
    	{{ lab.lab_name }}
    	{{ lab.lab_description }}
    	{{ lab.no_workers }}
    	{{ lab.no_doctors }}
    	{{ lab.lab_open_time }}
    	{{ lab.lab_close_time }}
    	</p>

    </div>
   </div>
</section>

{% endblock %}

services/templates/services/services.html
{% extends 'mainpage/base.html' %}
{% block title %} Our Services {% load staticfiles %}{% endblock %}
{% block body %}
<section class="service">
  <div class="container">
      <div class="row">
          <h2> Our services </h2>
          <hr class="line">
          {% for i in service_details %}
            <div class="col-md-4 col-sm-6">
              <div class="single-service">
                <div class="single-service-img">
                  <div class="service-img">
                    <img class="img-responsive" src="{% static 'images/Operationtheatre.jpg' %}" alt="">
                  </div>
                </div>
                <div class="single-service-text">
                  <h3>{{ i.service_name }}</h3>
                  <p> {{ i.service_details }}</p>
                  {% if i.service_name == "Rooms" %}
                    <div class="readmore_area">
                      <a data-hover="Read More" href="{% url 'services:rooms' %}"><span>Read More</span></a>
                    </div>
                  {% endif %}
                </div>
                
            </div>
          </div>
        {% endfor %}
        {% for i in labs %}
          <div class="col-md-4 col-sm-6">
              <div class="single-service">
                <div class="single-service-img">
                  <div class="service-img">
                    <img class="img-responsive" src="{% static 'images/Operationtheatre.jpg' %}" alt="">
                  </div>
                </div>
                <div class="single-service-text">
                  <h3>{{ i.lab_name }}</h3>
                  <p> {{ i.lab_description }}</p>
                </div>
                <div class="readmore_area">
                  <a data-hover="Read More" href="{% url 'services:lab_details' i.lab_id %}"><span>Read More</span></a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
  </div>

</section>
{% endblock %}